### ISSUE TITLE
It would be cool to have all the levels of all the indexes having the right names.

### ISSUE THREAD

**Issue by nigolred** [SESAM-Polimi/MARIO#11]
![image](https://user-images.githubusercontent.com/54635332/156880596-f084b187-e956-4e9c-a7ea-594c8aafe725.png)

Es. names=['Region','Level','Consumption category']

**Comment by mohammadamint** [comment]
Fixed.

The names should remain consistent after any transformation on the data. The issue is solved through commit #88f6d681b50c9b3d6ebbb5f541774d885b546180
