### ISSUE TITLE
Misleading error message for `parse_eurostat`

### ISSUE THREAD

**Issue by maximikos** [SESAM-Polimi/MARIO#2]
Following the [documentation](https://mario-suite.readthedocs.io/en/latest/htmls/parseEUROSTAT.html) for the Eurostat-parsing functionality, I ran into below error ("non-corresponding years"). This is unexpected since I was strictly following the documentation, i.e. did everything as described there. Any ideas why that happens and how to get my SUTs?

`---------------------------------------------------------------------------
WrongInput                                Traceback (most recent call last)
c:\Users\maximiko\IO-testbed\Eurostat_MARIO.py in <module>
----> 18 italy_sut = parse_eurostat(
      19     supply_path = supply_path,
      20     use_path = use_path,
      21     region = "Italy",
      22     year = 2011

~\Anaconda3\envs\pymrio\lib\site-packages\mario\tools\parsersclass.py in parse_eurostat(supply_path, use_path, region, year, consumption_categories, factors_of_production, imports, model, name, calc_all, **kwargs)
    432     table = "SUT"
    433     if table == "SUT":
--> 434         matrices, indeces, units = eurostat_sut(
    435             supply_path,
    436             use_path,

~\Anaconda3\envs\pymrio\lib\site-packages\mario\tools\tableparser.py in eurostat_sut(supply_path, use_path, region, selected_year, consumption_categories, factors_of_production, imports)
    992         years = supply_years
    993     else:
--> 994         raise WrongInput("No correspondance between years of use and supply tables")
    995 
    996     "Warning on supply in IxP format, Use in PxI format"

WrongInput: No correspondance between years of use and supply tables`

**Comment by mohammadamint** [comment]
Dear @maximikos this error should happen when the giver year does not correspond to the table you downloaded from Eurostat. but there is the possibility that the error is not handled correctly due to the structure of the database download. 
would you please send your database then I can check and we may improve the error message to be more clear?

**Comment by LorenzoRinaldi** [comment]
Dear @maximikos I tested the function and it works if you download tables in M€ only (so selecting just one unit of measure). We will improve the example provided on the documentation and certainly we will also work on making the eurostat parser more general and flexible to different table formats. In case you face the same issue, please send your database we will test it together with @mohammadamint.

**Comment by maximikos** [comment]
Hi Mohammad,

 

Thanks for your reply! I downloaded the two files according to how it is described in the documentation. After the import with those did not work, I removed the entries for the national currencies so that only the tables in € were left (see attached) – but that also did not work.

 

Any idea what might have gone wrong?

 

Max

**Comment by mohammadamint** [comment]
@maximikos there are a couple of small issues with the validation of the database format from Eurostat. we are fixing the issues and the new version will be uploaded very soon. AS we just published the first release there are minor issues with some of the functions and we are fixing them. Unfortunately, I can't find the attached file. Would you please send it by email? so we can spot the error. Moreover, you can also reshape your database to the acceptable excel format for mario. 
Looking forward to your email!!
