### ISSUE TITLE
search function minor improvement

### ISSUE THREAD

**Issue by LorenzoRinaldi** [SESAM-Polimi/MARIO#27]
The search function should not be case sensitive. For instance, if the user run this command:

db.search("Sector","electricity") 

he will not be able to track for sectors named "Electricity..." with capital "E". 
It would be super-useful to improve this making the function not case-sensitive

**Comment by mohammadamint** [comment]
fixed by commit :  cd9e17970c176c931ad219669dbe247a5fea86ab
